### ISSUE TITLE
Deploying on Gatsby Cloud problem

### ISSUE THREAD

**Issue by Yerbaneyro** [Secret-Developers-Base/code2137#4]
Generating JavaScript bundles failed at node_modules/@fontsource/righteous/index.css 

```
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
Error: Cannot find module css-loader/locals
Require stack:
- /usr/src/app/www/node_modules/typings-for-css-modules-loader/lib/index.js
- /usr/src/app/www/node_modules/loader-runner/lib/loadLoader.js
- /usr/src/app/www/node_modules/loader-runner/lib/LoaderRunner.js
- /usr/src/app/www/node_modules/webpack/lib/NormalModule.js
- /usr/src/app/www/node_modules/webpack/lib/ModuleFilenameHelpers.js
- /usr/src/app/www/node_modules/webpack/lib/index.js
- /home/gatsby/.nvm/versions/node/v16.15.0/lib/node_modules/@gatsby-cloud-pkg/gatsby-inc-build-cli/dist/index.js
- /home/gatsby/.nvm/versions/node/v16.15.0/lib/node_modules/@gatsby-cloud-pkg/gatsby-inc-build-cli/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/usr/src/app/www/node_modules/typings-for-css-modules-loader/lib/index.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (/usr/src/app/www/node_modules/loader-runner/lib/loadLoader.js:19:17)
    at iteratePitchingLoaders (/usr/src/app/www/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/usr/src/app/www/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule.doBuild (/usr/src/app/www/nodemodules/webpack/lib/NormalModule.js:819:3)
    at NormalModule.build (/usr/src/app/www/

For more details see https://gatsby.dev/issue-how-to

Generating JavaScript bundles failed at node_modules/@fontsource/roboto/index.css 

Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
Error: Cannot find module css-loader/locals
Require stack:
- /usr/src/app/www/node_modules/typings-for-css-modules-loader/lib/index.js
- /usr/src/app/www/node_modules/loader-runner/lib/loadLoader.js
- /usr/src/app/www/node_modules/loader-runner/lib/LoaderRunner.js
- /usr/src/app/www/node_modules/webpack/lib/NormalModule.js
- /usr/src/app/www/node_modules/webpack/lib/ModuleFilenameHelpers.js
- /usr/src/app/www/node_modules/webpack/lib/index.js
- /home/gatsby/.nvm/versions/node/v16.15.0/lib/node_modules/@gatsby-cloud-pkg/gatsby-inc-build-cli/dist/index.js
- /home/gatsby/.nvm/versions/node/v16.15.0/lib/node_modules/@gatsby-cloud-pkg/gatsby-inc-build-cli/bin/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/usr/src/app/www/node_modules/typings-for-css-modules-loader/lib/index.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (/usr/src/app/www/node_modules/loader-runner/lib/loadLoader.js:19:17)
    at iteratePitchingLoaders (/usr/src/app/www/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/usr/src/app/www/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule.doBuild (/usr/src/app/www/nodemodules/webpack/lib/NormalModule.js:819:3)
    at NormalModule.build (/usr/src/app/www/

```
For more details see https://gatsby.dev/issue-how-to

Error pojawia się przy próbie deploy na Gatsby Cloud, lokalnie build jest ok. Może być coś z paczkami. Trzeba ogarnąć :P

**Comment by Yerbaneyro** [comment]
Solved by removing easyfonts and fontsource...looks like it's some conflict betwen them and sass modules, at last with our styles structure. W going to implement fonts manualy.
